# This is a config for E2B sandbox template.
# You can use template ID (jkjwa3n1848wsq44p4xp) or template name (vibe-nextjs-test-tmp) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-test-tmp") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-test-tmp") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-test-tmp')

team_id = "4980e10a-b041-4516-b194-15456ed27cbc"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-test-tmp"
template_id = "jkjwa3n1848wsq44p4xp"
